### ISSUE TITLE
Dionaea os fingerprinting

### ISSUE THREAD

**Issue by ahmedkhiar** [DinoTools/dionaea#216] opened 2018-06-19 10:59 UTC
Hello all,

I deployed dionaea with smb service enabled, the problem I m facing is that with a simple nmap probe, it detect my real operating system which is linux, is there a way to change the fingerprint so that the nmap probe returns windows os instead of linux ?

Thank you.

**Comment by jaredfrees** [comment] 2018-06-25 18:23
Changing the mac address on your machine can fix this.

**Comment by phibos** [comment] 2018-07-24 23:06
Duplicate of #222. Closing the issue.

**Closed by phibos** 2018-07-24 23:06 UTC
Labels: duplicate
