### ISSUE TITLE
About ppa:honeynet/nightly dionaea version

### ISSUE THREAD

**Issue by royikle** [DinoTools/dionaea#220] opened 2018-06-28 02:56 UTC
Hi all
The dionaea latest version I can see is 0.6.0.
I just want to know, is the ppa:honeynet/nightly planning on updating PPA for 0.8.0?
Best Regards.

**Comment by Fathonizep** [comment] 2018-07-17 14:13
already sir.

**Comment by phibos** [comment] 2018-08-25 21:03
Duplicate of #198

**Closed by phibos** 2018-08-25 21:03 UTC
